# -*- coding: utf-8 -*-
"""diffeomorphism_gauge_test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10oZFZ2MTQXQO4s8zV2Ki8ZMEnHwe588I
"""

# -*- coding: utf-8 -*-

import sympy as sp

sp.init_printing()

t, x, y, z = sp.symbols("t x y z", real=True)

coords = [t, x, y, z]
coord_names = ["t", "x", "y", "z"]

kappa = sp.symbols("kappa", real=True, nonzero=True)

a = sp.Function("a")(t)

phi = sp.Function("phi")(t, x, y, z)

A_x = sp.Function("A_x")(t, x, y, z)
A_y = sp.Function("A_y")(t, x, y, z)
A_z = sp.Function("A_z")(t, x, y, z)

A_mu = [phi, A_x, A_y, A_z]

eta = sp.diag(-1, 1, 1, 1)

print("\n============================================================")
print("0. BASIC DEFINITIONS")
print("============================================================")
print("Coordinates:")
print(coord_names)
print("\nElectromagnetic potential:")
print("A_mu = (phi, A_x, A_y, A_z)")
print("\nTetrad ansatz:")
print("e^0 = (1 + kappa phi) dt + kappa A_i dx^i")
print("e^a = a(t) dx^a")

e = sp.Matrix([
    [1 + kappa*phi, kappa*A_x, kappa*A_y, kappa*A_z],
    [0,              a,         0,         0        ],
    [0,              0,         a,         0        ],
    [0,              0,         0,         a        ]
])

print("\n============================================================")
print("1. TETRAD MATRIX e^A_mu")
print("============================================================")
sp.pprint(e)

print("\nLaTeX:")
print(sp.latex(e))

e_inv = sp.simplify(e.inv())

print("\n============================================================")
print("2. INVERSE TETRAD E_A^mu")
print("============================================================")
sp.pprint(e_inv)

print("\nCheck: e_inv * e = I")
sp.pprint(sp.simplify(e_inv * e))

print("\nCheck: e * e_inv = I")
sp.pprint(sp.simplify(e * e_inv))

g = sp.simplify(e.T * eta * e)

print("\n============================================================")
print("3. METRIC g_mu_nu")
print("============================================================")
sp.pprint(g)

print("\nLaTeX:")
print(sp.latex(g))

print("\nMetric components:")
for mu in range(4):
    for nu in range(4):
        val = sp.simplify(g[mu, nu])
        if val != 0:
            print(f"g_{coord_names[mu]}{coord_names[nu]} =")
            sp.pprint(val)
            print()

print("\n============================================================")
print("4. g_0i TERMS")
print("============================================================")

for i, name in enumerate(["x", "y", "z"], start=1):
    print(f"g_0{name} =")
    sp.pprint(sp.simplify(g[0, i]))
    print()

def partial(expr, mu):
    return sp.diff(expr, coords[mu])

F = sp.MutableDenseMatrix(4, 4, lambda i, j: 0)

for mu in range(4):
    for nu in range(4):
        F[mu, nu] = sp.simplify(
            partial(A_mu[nu], mu) - partial(A_mu[mu], nu)
        )

print("\n============================================================")
print("5. ELECTROMAGNETIC FIELD TENSOR F_mu_nu")
print("============================================================")
sp.pprint(F)

print("\nNonzero F_mu_nu components:")
for mu in range(4):
    for nu in range(4):
        val = sp.simplify(F[mu, nu])
        if val != 0:
            print(f"F_{coord_names[mu]}{coord_names[nu]} =")
            sp.pprint(val)
            print()

print("\n============================================================")
print("6. DIFFEOMORPHISM GAUGE / INTEGRABILITY TEST")
print("============================================================")
print("Temporal tetrad:")
print("e^0 = dt + kappa A")
print("\nCondition for e^0 to be a coordinate differential:")
print("e^0 = d tau")
print("tau = t + kappa lambda")
print("A = d lambda")
print("F = dA = 0")

print("\nTest components:")

tests = [
    ("F_tx", F[0, 1]),
    ("F_ty", F[0, 2]),
    ("F_tz", F[0, 3]),
    ("F_xy", F[1, 2]),
    ("F_xz", F[1, 3]),
    ("F_yz", F[2, 3]),
]

for label, expr in tests:
    print(f"{label} =")
    sp.pprint(sp.simplify(expr))
    print()

T_lorentz = {}

for A in range(4):
    for mu in range(4):
        for nu in range(4):
            T_lorentz[(A, mu, nu)] = sp.simplify(
                partial(e[A, nu], mu) - partial(e[A, mu], nu)
            )

print("\n============================================================")
print("7. LORENTZ-INDEXED TORSION T^A_mu_nu")
print("============================================================")

print("\nNonzero T^A_mu_nu components:")
for key, val in T_lorentz.items():
    if val != 0:
        A, mu, nu = key
        print(f"T^{A}_{{{coord_names[mu]}{coord_names[nu]}}} =")
        sp.pprint(val)
        print()

T0 = sp.MutableDenseMatrix(4, 4, lambda i, j: 0)

for mu in range(4):
    for nu in range(4):
        T0[mu, nu] = T_lorentz[(0, mu, nu)]

difference_T0_kF = sp.simplify(T0 - kappa*F)

print("\n============================================================")
print("8. MAIN CHECK: T^0_mu_nu - kappa F_mu_nu")
print("============================================================")
sp.pprint(difference_T0_kF)

if difference_T0_kF == sp.zeros(4):
    print("\nRESULT:")
    print("T^0_mu_nu = kappa F_mu_nu verified.")
else:
    print("\nWARNING:")
    print("T^0_mu_nu - kappa F_mu_nu is not zero.")

T_coord = {}

for rho in range(4):
    for mu in range(4):
        for nu in range(4):
            expr = 0
            for A in range(4):
                expr += e_inv[rho, A] * T_lorentz[(A, mu, nu)]
            T_coord[(rho, mu, nu)] = sp.simplify(expr)

print("\n============================================================")
print("9. COORDINATE-INDEXED TORSION T^rho_mu_nu")
print("============================================================")

print("\nNonzero T^rho_mu_nu components:")
for key, val in T_coord.items():
    if val != 0:
        rho, mu, nu = key
        print(f"T^{coord_names[rho]}_{{{coord_names[mu]}{coord_names[nu]}}} =")
        sp.pprint(val)
        print()

Tv = [0]*4

for mu in range(4):
    expr = 0
    for nu in range(4):
        expr += T_coord[(nu, nu, mu)]
    Tv[mu] = sp.simplify(expr)

print("\n============================================================")
print("10. TORSION VECTOR T_mu = T^nu_nu_mu")
print("============================================================")

for mu in range(4):
    print(f"T_{coord_names[mu]} =")
    sp.pprint(Tv[mu])
    print()

lambda_func = sp.Function("lambda")(t, x, y, z)

pure_A_mu = [
    sp.diff(lambda_func, t),
    sp.diff(lambda_func, x),
    sp.diff(lambda_func, y),
    sp.diff(lambda_func, z)
]

F_pure = sp.MutableDenseMatrix(4, 4, lambda i, j: 0)

for mu in range(4):
    for nu in range(4):
        F_pure[mu, nu] = sp.simplify(
            partial(pure_A_mu[nu], mu) - partial(pure_A_mu[mu], nu)
        )

print("\n============================================================")
print("11. PURE GAUGE TEST: A_mu = partial_mu lambda")
print("============================================================")

print("\nF_mu_nu[A = d lambda] =")
sp.pprint(F_pure)

if F_pure == sp.zeros(4):
    print("\nRESULT:")
    print("For A_mu = partial_mu lambda, F_mu_nu = 0 verified.")
else:
    print("\nWARNING:")
    print("F_pure is not zero.")

e0_pure = [
    1 + kappa*sp.diff(lambda_func, t),
    kappa*sp.diff(lambda_func, x),
    kappa*sp.diff(lambda_func, y),
    kappa*sp.diff(lambda_func, z)
]

T0_pure = sp.MutableDenseMatrix(4, 4, lambda i, j: 0)

for mu in range(4):
    for nu in range(4):
        T0_pure[mu, nu] = sp.simplify(
            partial(e0_pure[nu], mu) - partial(e0_pure[mu], nu)
        )

print("\nT^0_mu_nu[A = d lambda] =")
sp.pprint(T0_pure)

if T0_pure == sp.zeros(4):
    print("\nRESULT:")
    print("For A_mu = partial_mu lambda, T^0_mu_nu = 0 verified.")
    print("In this case, e^0 = d(t + kappa lambda).")
else:
    print("\nWARNING:")
    print("T0_pure is not zero.")

print("\n============================================================")
print("12. ELECTROMAGNETIC INVARIANT F_mu_nu F^mu_nu")
print("============================================================")

g_inv = sp.simplify(g.inv())

F_up = sp.MutableDenseMatrix(4, 4, lambda i, j: 0)

for mu in range(4):
    for nu in range(4):
        expr = 0
        for alpha in range(4):
            for beta in range(4):
                expr += g_inv[mu, alpha] * g_inv[nu, beta] * F[alpha, beta]
        F_up[mu, nu] = sp.simplify(expr)

F2 = 0

for mu in range(4):
    for nu in range(4):
        F2 += F[mu, nu] * F_up[mu, nu]

F2 = sp.simplify(F2)

print("\nF_mu_nu F^mu_nu =")
sp.pprint(F2)

L_EM = sp.simplify(-sp.Rational(1, 4) * F2)

print("\nL_EM = -1/4 F_mu_nu F^mu_nu =")
sp.pprint(L_EM)