# -*- coding: utf-8 -*-
"""Elemantary_Mathematical_Objects.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pGuhoc8TQxZ-h3chgNUKEUvMlpzBa0F4
"""

import sympy as sp

sp.init_printing()

t, x, y, z = sp.symbols('t x y z', real=True)
coords = [t, x, y, z]

c = sp.symbols('c', positive=True, real=True)
kappa = sp.symbols('kappa', real=True)

a = sp.Function('a')(t)

phi = sp.Function('phi')(t, x, y, z)

Ax = sp.Function('A_x')(t, x, y, z)
Ay = sp.Function('A_y')(t, x, y, z)
Az = sp.Function('A_z')(t, x, y, z)

eta = sp.diag(-1, 1, 1, 1)


e = sp.Matrix([
    [1 + kappa*phi, kappa*Ax, kappa*Ay, kappa*Az],
    [0,             a,        0,        0],
    [0,             0,        a,        0],
    [0,             0,        0,        a]
])

print("\ne^A_mu =\n")
sp.simplify(e)

g = sp.simplify(e.T * eta * e)

print("\ng_mu_nu =\n")
sp.simplify(g)

g_inv = sp.simplify(g.inv())

print("\ng^mu_nu =\n")
sp.simplify(g_inv)

det_g = sp.factor(g.det())

print("\ndet(g) =")
sp.simplify(det_g)

T = {}

for A in range(4):
    for mu in range(4):
        for nu in range(mu + 1, 4):

            component = sp.simplify(
                sp.diff(e[A, nu], coords[mu])
                - sp.diff(e[A, mu], coords[nu])
            )

            if component != 0:
                T[(A, mu, nu)] = component

for key, component in T.items():

    A, mu, nu = key

sp.simplify(T.get((0, 0, 1), 0))

sp.simplify(T.get((0, 0, 2), 0))

sp.simplify(T.get((0, 0, 3), 0))

sp.simplify(T.get((0, 1, 2), 0))

sp.simplify(T.get((0, 1, 3), 0))

sp.simplify(T.get((0, 2, 3), 0))

sp.simplify(T.get((1, 0, 1), 0))

sp.simplify(T.get((2, 0, 2), 0))

sp.simplify(T.get((3, 0, 3), 0))

inverse_tetrad = sp.simplify(e.inv())

T_spacetime = sp.MutableDenseNDimArray.zeros(4, 4, 4)

for rho in range(4):
    for mu in range(4):
        for nu in range(4):
            T_spacetime[rho, mu, nu] = sp.simplify(
                sum(
                    inverse_tetrad[rho, A] * T_lorentz[A, mu, nu]
                    for A in range(4)
                )
            )

sp.simplify(T_spacetime[0, 0, 1])

sp.simplify(T_spacetime[0, 0, 2])

sp.simplify(T_spacetime[0, 0, 3])

sp.simplify(T_spacetime[0, 1, 2])

sp.simplify(T_spacetime[0, 1, 3])

sp.simplify(T_spacetime[0, 2, 3])

sp.simplify(T_spacetime[1, 0, 1])

sp.simplify(T_spacetime[2, 0, 2])

sp.simplify(T_spacetime[3, 0, 3])